---
- hosts: vms
  tasks:
    - name: Affiche command
      debug:
        msg: "vgcreate {{ item.vgname }} with disk {{ item.devices }}"
      loop: "{{ ansible_local.lvm_config.volum_groups }}"
        
    - name: Affiche command
      debug:
        msg: "lvname {{ item.lvname }} on vg {{ item.vgname }} size {{ item.lvsize }}"
      loop: "{{  ansible_local.lvm_config.logical_volums}}"
   # - name: debug
   #   debug:
   #     var:  ansible_local


