---
# tasks file for sap_prerequisites

- name: Enable rhel-9-for-x86_64-sap-es4-solutions-rpms
  community.general.rhsm_repository:
    name: rhel-9-for-x86_64-sap-solutions-e4s-rpms

- name: Install software packages
  ansible.builtin.include_tasks: sap_install_packages.yml

- name: Create Users and groups
  ansible.builtin.include_tasks: sap_create_users_grps.yml

- name: Install and configure tuned
  block:
    - name: Install tuned package
      ansible.builtin.dnf:
        name: tuned-profiles-sap-hana
        state: latest
    - name: Start and Enable tuned
      ansible.builtin.systemd:
        name: tuned
        enabled: true
        state: started
    - name: Active profile sap-hana
      ansible.builtin.shell: "tuned-adm profile sap-hana; tuned-adm active"

  rescue:
    - name: Something wrong when enable tuned
      ansible.builtin.debug:
        msg: "Something wrong when enable tuned"


- name: Turn Off auto-numa balancing
  ansible.posix.sysctl:
    name: kernel.numa_balancing
    value: '0'
    sysctl_set: true
    state: present
    reload: true

- name: Disable kdump and Turn off auto-numa balancing
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: 
    - kdump
    - numad
  ignore_errors: true



- name: Create VG
  ansible.builtin.include_tasks: sap_create_vg_lv.yml
  tags:
    - createvg

- name : Disable Transparent HugePages
  ansible.builtin.shell: ' echo never > /sys/kernel/mm/transparent_hugepage/enabled; grubby --update=ALL --args="transparent_hugepage=never"'
  #when: var_env == "bdd"

- name : Configure Limits
  community.general.pam_limits:
    dest: /etc/security/limits.d/99-sap.conf
    domain: "@sapsys"
    limit_type: "{{ item }}"
    limit_item: "nproc"
    value: "unlimited"
  loop:
    - hard
    - soft
  tags:
    - limits

- name: Exclude Some file from systemd.tmpfiles
  ansible.builtin.template:
    src: sap_tmpfs.j2
    dest: /etc/tmpfiles.d/sap.conf
  tags:
    - exclude_tmpfiles

- name: Configure SELinux to permissive
  ansible.builtin.include_tasks: sap_selinux.yml
  tags:
    - selinux
