---
# tasks file for sap_prerequisites

- name: Install software packages
  ansible.builtin.include_tasks: sap_install_packages.yml

- name: Create Users and groups
  ansible.builtin.include_tasks: sap_create_users_grps.yml

- name: Install and configure tuned
  block:
    - name: Install tuned package
      ansible.builtin.dnf:
        name: tuned-profiles-sap-hana
        state: latest
    - name: Start and Enable tuned
      ansible.builtin.systemd:
        name: tuned
        enabled: true
        state: started
    - name: Active profile sap-hana
      ansible.builtin.shell: "tuned-adm profile sap-hana; tuned-adm active"
      changed_when: false
  rescue:
    - name: Something wrong when enable tuned
      ansible.builtin.debug:
        msg: "Something wrong when enable tuned"


- name: Turn Off auto-numa balancing
  ansible.posix.sysctl:
    name: kernel.numa_balancing
    value: '0'
    sysctl_set: true
    state: present
    reload: true

- name: Disable kdump and Turn off auto-numa balancing
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: 
    - kdump
    - numad




